#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

platform: x86
configuration: Release

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\NyaaSnap

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: NyaaSnap\bin\x86\Release\NyaaSnap.exe
    name: NyaaSnap
    type: zip
